sudo: required
dist: trusty
before_install:
  - sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended
    texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-xetex fonts-lmodern latex-xcolor texlive-bibtex-extra texlive-lang-cjk biber dvipng
  - wget -c https://sourceforge.net/projects/zjuthesis/files/fonts.tar.gz/download -O
    fonts.tar.gz && tar xzf fonts.tar.gz && sudo mkdir -p /usr/share/fonts/truetype/custom/
    && sudo mv fonts/* /usr/share/fonts/truetype/custom/ && sudo fc-cache -f -v
script:
  - cd proposal && make
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis CI"
  - git config --global user.email "builds@travis-ci.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - git push -q https://$TAGPERM@github.com/$TRAVIS_REPO_SLUG --tags
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: proposal/main.pdf
  skip_cleanup: true
